export const MODALITIES = [
  'RL_GYM',
  'CODE_AGENT',
  'EVAL_INFRA',
  'PROMPT_ENGINEERING',
  'FINETUNING',
  'INFERENCE_OPT',
  'DATASET_CURATION',
] as const;

export type Modality = typeof MODALITIES[number];

export const OUTREACH_STATUSES = [
  'not_contacted',
  'reached_out',
  'responded',
  'not_interested',
  'interviewing',
  'hired',
] as const;

export type OutreachStatus = typeof OUTREACH_STATUSES[number];

export const MODALITY_KEYWORDS: Record<Modality, string[]> = {
  RL_GYM: [
    'gymnasium',
    'gym',
    'PPO',
    'A3C',
    'SAC',
    'TD3',
    'DQN',
    'DDPG',
    'reinforcement-learning',
    'reinforcement learning',
    'RL',
    'policy-gradient',
    'policy gradient',
    'actor-critic',
    'actor critic',
    'reward-shaping',
    'reward shaping',
    'reward-modeling',
    'reward modeling',
    'agent-training',
    'agent training',
    'environment-wrapper',
    'stable-baselines',
    'ray-rllib',
    'openai-gym',
    'custom-gym',
  ],
  CODE_AGENT: [
    'code-generation',
    'code generation',
    'agentic',
    'autonomous-coding',
    'autonomous coding',
    'SWE-bench',
    'HumanEval',
    'code-interpreter',
    'code interpreter',
    'tool-use',
    'tool use',
    'LLM-agent',
    'LLM agent',
    'function-calling',
    'function calling',
    'code-completion',
    'code completion',
    'AI-developer',
    'copilot',
    'langchain',
    'llama-index',
    'semantic-kernel',
  ],
  EVAL_INFRA: [
    'eval-framework',
    'eval framework',
    'benchmark',
    'benchmarking',
    'metrics',
    'evaluation-harness',
    'evaluation harness',
    'leaderboard',
    'test-suite',
    'test suite',
    'grading',
    'model-evaluation',
    'model evaluation',
    'performance-testing',
    'performance testing',
    'quality-metrics',
    'A/B-testing',
    'pytest',
    'hypothesis',
    'benchmark-datasets',
  ],
  PROMPT_ENGINEERING: [
    'prompt-engineering',
    'prompt engineering',
    'prompt-optimization',
    'prompt optimization',
    'few-shot',
    'few shot',
    'chain-of-thought',
    'chain of thought',
    'CoT',
    'prompt-tuning',
    'prompt tuning',
    'in-context-learning',
    'in context learning',
    'ICL',
  ],
  FINETUNING: [
    'fine-tuning',
    'fine tuning',
    'finetuning',
    'PEFT',
    'LoRA',
    'QLoRA',
    'adapter',
    'parameter-efficient',
    'parameter efficient',
    'training',
    'supervised-fine-tuning',
    'SFT',
    'instruction-tuning',
    'instruction tuning',
  ],
  INFERENCE_OPT: [
    'inference',
    'optimization',
    'quantization',
    'pruning',
    'distillation',
    'TensorRT',
    'ONNX',
    'vLLM',
    'TGI',
    'text-generation-inference',
    'model-serving',
    'model serving',
    'latency-optimization',
    'throughput',
  ],
  DATASET_CURATION: [
    'dataset',
    'data-curation',
    'data curation',
    'data-collection',
    'data collection',
    'annotation',
    'labeling',
    'synthetic-data',
    'synthetic data',
    'data-quality',
    'data quality',
    'data-cleaning',
    'data cleaning',
    'human-feedback',
    'RLHF',
  ],
};

export const MODALITY_LABELS: Record<Modality, string> = {
  RL_GYM: 'RL Gym',
  CODE_AGENT: 'Code Agent',
  EVAL_INFRA: 'Eval Infrastructure',
  PROMPT_ENGINEERING: 'Prompt Engineering',
  FINETUNING: 'Fine-tuning',
  INFERENCE_OPT: 'Inference Optimization',
  DATASET_CURATION: 'Dataset Curation',
};

export const OUTREACH_STATUS_LABELS: Record<OutreachStatus, string> = {
  not_contacted: 'Not Contacted',
  reached_out: 'Reached Out',
  responded: 'Responded',
  not_interested: 'Not Interested',
  interviewing: 'Interviewing',
  hired: 'Hired',
};

export const OUTREACH_STATUS_COLORS: Record<OutreachStatus, string> = {
  not_contacted: 'bg-neutral-800 text-neutral-300',
  reached_out: 'bg-blue-600/20 text-blue-400 border-blue-600/20',
  responded: 'bg-green-600/20 text-green-400 border-green-600/20',
  not_interested: 'bg-red-600/20 text-red-400 border-red-600/20',
  interviewing: 'bg-amber-600/20 text-amber-400 border-amber-600/20',
  hired: 'bg-green-600/20 text-green-400 border-green-600/20',
};
